name: build
on:
    workflow_dispatch:
          inputs:
              publish:
                  description: Publish to Modrinth and CurseForge
                  required: true
                  default: "false"
              patch:
                  description: Patch number, 0 for first (ex. Create 1.19.2 v0.5.0.g Patch N)
                  required: true
    pull_request:
    push:

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    env:
      PUBLISH_SUFFIX: snapshots
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      PATCH_NUMBER: ${{ github.event.inputs.patch }}
    steps:

      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build #OrPublish

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

      - name: publish to Modrinth and CurseForge
        if: ${{ github.event.inputs.publish }}
        run: ./gradlew publishMod
